### ISSUE TITLE
Feature request: Treat pipes as interfaces

### ISSUE THREAD

**Issue by pocc** [gcla/termshark#13] opened 2019-04-23 20:35 UTC
This is related to #9 Read from stdin insofar as unix redirection is concerned. The following works with wireshark reading from the pipe, but not termshark:

```bash
bash-5.0$ mkfifo mypipe
bash-5.0$ tshark -r file.pcap -w mypipe &
[1] 52917
bash-5.0$ termshark -i mypipe
Could not find network interface mypipe
```

**Comment by ZeroChaos-** [comment] 2019-07-24 03:50
wouldn't you use -r mypipe?  pipes are files

**Comment by pocc** [comment] 2019-07-24 06:54
`termshark` and `tshark` are both used in the example above. Can you provide a full counter-example so I can get a better idea of what you're talking about?

**Comment by ZeroChaos-** [comment] 2019-07-24 14:43
first establish the pipe and something writing to the pipe.  note, tcpdump, tshark, etc are writing to a FILE, that's what a pipe is.
```
theprophet /tmp # mkfifo mypipe
theprophet /tmp # tcpdump -i eth1 -w mypipe
dropped privs to tcpdump
```

Then try to read it
```
zero@theprophet /tmp % tcpdump -i mypipe
tcpdump: mypipe: You don't have permission to capture on that device
(socket: Operation not permitted)
zero@theprophet /tmp % tshark -i mypipe
Capturing on 'mypipe'
```

Note that tcpdump can't find an interface called mypipe (because one doesn't exist) but tshark seems to have some kind of special handling for pretending a file is an interface, but tcpdump doesn't.  tcpdump can read the file just fine

```
zero@theprophet /tmp % tcpdump -r mypipe
reading from file mypipe, link-type EN10MB (Ethernet)
```

This odd kind of special handling is confusing for users, and makes for confusion in the code.  pipes are files, read them like files.  That said, termshark doesn't seem to support reading pipes as files either, so this is still a feature request

**Comment by pocc** [comment] 2019-07-24 18:22
Cheers for the writeup. This is more descriptive than my initial post.

**Comment by gcla** [comment] 2019-08-15 02:42
I just committed a change for this. I'll mark this as - Duplicate of #9

**Comment by gcla** [comment] 2019-08-15 02:43
That didn't work. Duplicate of #9

**Closed as completed** 2019-08-16 02:56 UTC
Labels: feature request
