### ISSUE TITLE
termshark freezes on termux and never opens

### ISSUE THREAD

**Issue by ramsesramosgzz** [gcla/termshark#82] opened 2020-02-16 19:20 UTC
Im using aarch64 oneplus 6 and i remember trying termshark on termux in a arm nexus5 and worked ok but now that i tried to open it on the oneplus 6 it never opens because once i type termshark it freezes so i have to manually close termux, i tried this with different repos, different phones and i have the same result, first i do apt update && upgrade , pkg install termux-api , pkg install root-repo, and then pkg install termshark after that i just type termshark and its when this happens, any ideas?

**Comment by gcla** [comment] 2020-02-16 20:39
Hi @ramsesramosgzz  - thanks for the report, sorry for the trouble :(

I tried to do something android-specific if termshark is run on android with no arguments. My idea was to launch an android file-picker, and then provide the result from that file-picker back to termshark to load up. I bet that's the cause of the problem. I do that using utilities from the Termux::API package. Could you tell me what happens if you launch termux then type

```
termux-storage-get termux
```

from your termux home directory?

**Comment by ramsesramosgzz** [comment] 2020-02-22 18:58
Hello, first of all thank you for your reply and sorry for my late reply.. i did just as you instructed i opened my termux and typed and executed termux-storage-get termux and it freezed the same way like when i executed termshark it just stays there doing nothing

[Here's a video](https://hackraisers.com/termux.mp4)

as mentioned above the same thing happens when i type termshark

**Comment by gcla** [comment] 2020-08-24 02:36
Hi @ramsesramosgzz - sorry for the long period of inaction on this bug. I'm sure this problem is real, but I don't have an android device that is able to reproduce it. :-( The piece of functionality that is broken in your case is launching an android file picker that lets you find a pcap to open in termshark. Another way to launch is to just provide the pcap on the command line of termux e.g.
```
termshark -r /path/to/my/file.pcap
```
It's easier to find it with the picker, but maybe the second way will work for you? If you've run `termux-setup-storage`, then there are several handy symlinks in your termux home directory - so if you had downloaded the pcap via e.g. chrome on your phone, then you can load it in termshark like this:
```
termshark -r ~/storage/downloads/file.pcap
```
If running termshark somewhere other than android, running `termshark` with no arguments will start termshark listening on the first interface in those listed with `termshark -D`. But because you can't easily sniff packets on a regular android phone, I changed the default behavior on android for launching without arguments to use the file-picker instead. If you have a rooted phone and did intend to listen for packets, you can run:
```
termshark -D
```
to list the available interfaces, then pick one by name or number and start with `-i` e.g.
```
termshark -i 1
```
Hope this helps even if it's not a fix.

**Comment by gcla** [comment] 2021-04-30 04:02
Hi @ramsesramosgzz - sorry this bug was open for so long without help. I am at a loss really - I think I'd need to find a phone on which I can reproduce it. Maybe you've upgraded by now and the problem has gone away? (optimistic maybe)

**Comment by gcla** [comment] 2021-05-15 02:57
Closing for now. I left this too long. Let me know if the problem is still there.

**Closed as completed by gcla** 2021-05-15 02:57 UTC
Labels: bug
