### ISSUE TITLE
Feature request: Launch termshark on first interface if none specified

### ISSUE THREAD

**Issue by pocc** [gcla/termshark#8] opened 2019-04-23 09:24 UTC
First of all, congrats on launching a cool project!

I want termshark to launch on the first interface to mimic the behavior of tshark. Depending on how you have this set up, you could call tshark without interface arguments if termshark does not receive any. 

On the CLI, this will show you the first interface tshark sees (and will use):
`tshark -D | awk 'NR==1 { print $2}'`.

**Comment by gcla** [comment] 2019-04-23 15:00
Thanks for your kind words :-)

Yes, right now when you run termshark without args it just opens an empty tui. Your suggestion is much better, and it follows tshark. I'll make it happen!

**Comment by pocc** [comment] 2019-04-23 15:14
I'd like to contribute - mind if I take this one?

**Comment by gcla** [comment] 2019-04-23 15:15
Not at all, please do!

**Comment by sagis-tikal** [comment] 2019-04-23 16:00
Could it be a duplicate of the issue I opened? 
https://github.com/gcla/termshark/issues/5#issue-436040522

**Comment by pocc** [comment] 2019-04-23 16:02
@sagis-tikal Yes it is

**Closed as completed** 2019-04-24 02:25 UTC
